[package]
name = "bountypool"
version = "1.1.0"
description = "Decentralized gig economy bounty protocol on Stacks"
authors = ["Stacks Builder <builder@stacks.dev>"]
telemetry = false
cache_location = "./.clarinet"

[repl.costs_version]
version = 2

[repl.analysis]
passes = ["check_checker"]

[contracts.bountypool]
path = "contracts/bountypool.clar"
clarity_version = 2
epoch = 2.4

[devnet]
name = "bountypool-devnet"
bitcoin_node_p2p_port = 18444
bitcoin_node_rpc_port = 18445
stacks_node_rpc_port = 20443
orchestrator_port = 20445
postgres_port = 5432
bitcoin_node_image_url = "quay.io/hirosystems/bitcoind:devnet"
stacks_node_image_url = "quay.io/hirosystems/stacks-node:devnet"
miner_mnemonic = "twice kind fence tip hidden tilt action foxglove nearly neglect lens virtual scene leader pizza away worth gate gift hobby fourteen coach gather"
miner_derivation_path = "m/44'/5757'/0'/0/0"
