[project]
name = "bountypool"
authors = []
description = "Decentralized Bounty Board for Open Source Contributions"
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[contracts.bountypool]
path = "contracts/bountypool.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
